version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: monmotdepassefort123 
      MYSQL_DATABASE: hdm_todo_db        # Nom de la base de données par défaut
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql  

volumes:
  mysql-data:
